import os
import time
import random
import requests
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

API_URL = os.environ.get('API_URL', 'http://localhost:5000/api/logs')
SLEEP_INTERVAL = int(os.environ.get('SLEEP_INTERVAL', 5))

SEVERITIES = ['low', 'medium', 'high', 'critical']
HONEYPOTS = ['Cowrie-Node-1', 'Dionaea-Node-1', 'WebCam-Honeypot']
EVENT_TYPES = ['SSH_Login_Failed', 'FTP_Anonymous_Login', 'HTTP_Exploit_Attempt', 'SMB_RCE_Attempt', 'Port_Scan']

def generate_random_ip():
    return f"{random.randint(1, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}.{random.randint(1, 254)}"

def generate_mock_log():
    return {
        "severity": random.choice(SEVERITIES),
        "honeypot_name": random.choice(HONEYPOTS),
        "honeypot_type": "Mock_Sensor",
        "source_ip": generate_random_ip(),
        "event_type": random.choice(EVENT_TYPES),
        "description": "Mock attack generated by sensor",
        "raw_data": "{\"payload\": \"mock data\"}"
    }

def main():
    logger.info(f"Sensor started. Sending logs to {API_URL} every {SLEEP_INTERVAL} seconds.")
    
    # Wait for API to be ready
    time.sleep(10)
    
    while True:
        try:
            log_data = generate_mock_log()
            logger.info(f"Sending log: {log_data['event_type']} from {log_data['source_ip']}")
            
            response = requests.post(API_URL, json=log_data, timeout=5)
            
            if response.status_code == 201:
                logger.info(f"Successfully sent log. API Response: {response.json()}")
            else:
                logger.error(f"Failed to send log. Status Code: {response.status_code}, Response: {response.text}")
                
        except requests.exceptions.RequestException as e:
            logger.error(f"Connection error to API: {e}")
            
        time.sleep(SLEEP_INTERVAL)

if __name__ == '__main__':
    main()
